openapi: 3.2.0
info:
  title: Open edX Univertest API
  description: APIs for access to Open edX information
  contact:
    email: dl@kaznu.kz
  version: v1
servers:
- url: https://open.kaznu.kz/api
security:
- Basic: []
tags:
- name: univertest
paths:
  /univertest/:
    get:
      operationId: univertest_list
      description: ''
      tags:
      - univertest
      responses:
        '200':
          description: ''
      summary: Univertest list
      x-summary-source: derived
components:
  securitySchemes:
    Basic:
      type: http
      scheme: basic
